# -*- coding: utf-8 -*-

from health_acl import API_ACL_VMWARE_MANAGER_HEALTH
from platform_acl import API_ACL_VMWARE_MANAGER_PLATFORM
from datacenter_acl import API_ACL_VMWARE_MANAGER_DATACENTER
from folder_acl import API_ACL_VMWARE_MANAGER_FOLDER
from vm_acl import API_ACL_VMWARE_MANAGER_VM


def get_api_acl_map():

    API_ACL_VMWARE_MANAGER = dict()
    API_ACL_VMWARE_MANAGER.update(API_ACL_VMWARE_MANAGER_HEALTH)
    API_ACL_VMWARE_MANAGER.update(API_ACL_VMWARE_MANAGER_PLATFORM)
    API_ACL_VMWARE_MANAGER.update(API_ACL_VMWARE_MANAGER_DATACENTER)
    API_ACL_VMWARE_MANAGER.update(API_ACL_VMWARE_MANAGER_FOLDER)
    API_ACL_VMWARE_MANAGER.update(API_ACL_VMWARE_MANAGER_VM)
    
    return API_ACL_VMWARE_MANAGER
