# -*- coding: utf-8 -*-

from api.constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    ROLE_GLOBAL_ADMIN,
    ROLE_ZONE_ADMIN,
    ROLE_CONSOLE_ADMIN,
    ROLE_NORMAL_USER,
    ROLE_PARTNER,
    ROLE_AGENT,
)
from constants import (
    ACTION_VMWARE_MANAGER_FOLDER_DETAIL_FOLDER,
    ACTION_VMWARE_MANAGER_FOLDER_DETAIL_ROOT_FOLDER
)

API_ACL_VMWARE_MANAGER_FOLDER = {
    ACTION_VMWARE_MANAGER_FOLDER_DETAIL_FOLDER: {
        CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                      ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                      ROLE_PARTNER, ROLE_AGENT],
        CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                          ROLE_PARTNER, ROLE_AGENT]
    },
    ACTION_VMWARE_MANAGER_FOLDER_DETAIL_ROOT_FOLDER: {
        CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                      ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                      ROLE_PARTNER, ROLE_AGENT],
        CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                          ROLE_PARTNER, ROLE_AGENT]
    }
}
