# -*- coding: utf-8 -*-

from constants import (
    ACTION_VMWARE_MANAGER_PLATFORM_ADD_PLATFORM,
    ACTION_VMWARE_MANAGER_PLATFORM_CHECK_PLATFORM_CONNECTIVITY,
    ACTION_VMWARE_MANAGER_PLATFORM_DELETE_PLATFORM,
    ACTION_VMWARE_MANAGER_PLATFORM_DESCRIBE_PLATFORM,
    ACTION_VMWARE_MANAGER_PLATFORM_UPDATE_PLATFORM,
)
from api.constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    ROLE_GLOBAL_ADMIN,
    ROLE_ZONE_ADMIN,
    ROLE_CONSOLE_ADMIN,
    ROLE_NORMAL_USER,
    ROLE_PARTNER,
    ROLE_AGENT,
)


API_ACL_VMWARE_MANAGER_PLATFORM = {
        ACTION_VMWARE_MANAGER_PLATFORM_ADD_PLATFORM: {
            CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                          ROLE_PARTNER, ROLE_AGENT],
            CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                              ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                              ROLE_PARTNER, ROLE_AGENT],
        },
        ACTION_VMWARE_MANAGER_PLATFORM_CHECK_PLATFORM_CONNECTIVITY: {
            CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                          ROLE_PARTNER, ROLE_AGENT],
            CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                              ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                              ROLE_PARTNER, ROLE_AGENT],
        },
        ACTION_VMWARE_MANAGER_PLATFORM_DELETE_PLATFORM: {
            CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                          ROLE_PARTNER, ROLE_AGENT],
            CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                              ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                              ROLE_PARTNER, ROLE_AGENT],
        },
        ACTION_VMWARE_MANAGER_PLATFORM_DESCRIBE_PLATFORM: {
            CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                          ROLE_PARTNER, ROLE_AGENT],
            CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                              ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                              ROLE_PARTNER, ROLE_AGENT],
        },
        ACTION_VMWARE_MANAGER_PLATFORM_UPDATE_PLATFORM: {
            CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                          ROLE_PARTNER, ROLE_AGENT],
            CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                              ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN,
                              ROLE_PARTNER, ROLE_AGENT],
        }
}
